version: "3.9"

services:
  db_mysql:
    image: mysql:8
    env_file:
      - .env.mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "5555:3306"
    restart: on-failure

  db_mongo:
    image: mongo
    env_file:
      - .env.mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongodb:/data/db
    ports:
      - "27018:27017"
    restart: on-failure

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env.postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure
